### ISSUE TITLE
How can this be made to work on the MSI Z270I Gaming Pro Carbon AC?

### ISSUE THREAD

**Issue by newton** [nagisa/msi-rgb#46] opened 2018-12-29 05:39 UTC
My board seems to have the required NCT6795D chip.

msi-rgb prints no errors but doesn't affect the lights - they stay the default red.

**Comment by nagisa** [comment] 2018-12-29 11:51
Duplicate of #8.

Likely reason that by default the LEDs controlled are not those that you expect to be controlled. To fix it we need to figure out how the MSI’s gaming app switches between the rgb areas. There are two ways to help with that – do some analysis or lend hardware to those that would be willing do to it for you.

**Closed by nagisa** 2018-12-29 11:51 UTC
